# Generated by Django 4.1.2 on 2022-11-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('module', models.CharField(max_length=15)),
                ('filepath', models.FileField(null=True, upload_to='files/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
