# Generated by Django 4.1.2 on 2022-11-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_editsubject_class_belongs'),
        ('StudyMaterials', '0003_notes_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('submission_date', models.DateField()),
                ('module', models.CharField(max_length=15)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
