# Generated by Django 4.1.2 on 2022-11-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMaterials', '0004_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
