# Generated by Django 4.1.2 on 2022-11-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_editsubject_class_belongs'),
        ('StudyMaterials', '0005_delete_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='class_belongs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class'),
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
        ),
    ]
