# Generated by Django 4.1.2 on 2022-11-25 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_editsubject_semester'),
        ('StudyMaterials', '0006_notes_class_belongs_notes_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester'),
        ),
    ]
