# Generated by Django 4.1.2 on 2022-10-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='creator',
        ),
    ]
