# Generated by Django 4.1.2 on 2022-11-02 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_class_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
