# Generated by Django 4.1.2 on 2022-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_subject_subjectcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsubject',
            name='subjectcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
