# Generated by Django 4.1.2 on 2022-11-22 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0023_remove_user_is_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0016_editsubject_class_belongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('FIE', 'FIRST INTERNAL'), ('SIE', 'SECOND INTERNAL'), ('CTS', 'CLASS TESTS')], default=0, max_length=3)),
                ('total_score', models.CharField(max_length=50)),
                ('marked_score', models.CharField(max_length=50)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
