# Generated by Django 4.1.2 on 2022-11-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_editsubject_class_belongs'),
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='class_belongs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class'),
        ),
    ]
