# Generated by Django 4.1.2 on 2022-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0003_mark_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exam_type',
            field=models.CharField(choices=[('FIE', 'FIRST INTERNAL'), ('SIE', 'SECOND INTERNAL'), ('CTS', 'CLASS TESTS')], default=None, max_length=3),
        ),
    ]
