# Generated by Django 4.1.2 on 2022-11-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0020_semester_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_category', models.CharField(choices=[('MA', 'MANAGEMENT'), ('NR', 'NRI'), ('GO', 'GOVRNMENT')], max_length=12)),
                ('fees', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_date', models.DateField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.department')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
