# Generated by Django 4.1.2 on 2022-11-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_remove_user_quota_student_quota'),
        ('course', '0020_semester_order'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_category', models.CharField(max_length=12)),
                ('fees_paid', models.IntegerField(default=0)),
                ('payed_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.department')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
