# Generated by Django 4.1.2 on 2022-11-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_rename_fees_paid_feepaid_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepaid',
            name='student',
        ),
    ]
