# Generated by Django 4.1.2 on 2022-10-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('TR', 'Teacher'), ('PR', 'Principal')], max_length=2),
        ),
    ]
