# Generated by Django 4.1.2 on 2022-10-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admsn_no',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
