# Generated by Django 4.1.2 on 2022-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_student_admsn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default-avatar.jpg', null=True, upload_to='profile_image'),
        ),
    ]
