# Generated by Django 4.1.2 on 2022-10-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_editprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='editprofile',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='editprofile',
            name='parent_mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='editprofile',
            name='parent_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='editprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
