# Generated by Django 4.1.2 on 2022-11-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_user_position_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
