# Generated by Django 4.1.2 on 2022-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0025_user_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quota',
        ),
        migrations.AddField(
            model_name='student',
            name='quota',
            field=models.CharField(choices=[('MA', 'MANAGEMENT'), ('NR', 'NRI'), ('GO', 'GOVRNMENT')], default=0, max_length=2),
        ),
    ]
