# Generated by Django 4.1.2 on 2022-12-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_semester_order'),
        ('member', '0026_remove_user_quota_student_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_table', models.FileField(null=True, upload_to='files/')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
