# Generated by Django 4.1.2 on 2022-11-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('NA', 'NATIONAL'), ('SE', 'SECOND ASSIGNMENT'), ('CO', 'COLLEGE')], default=0, max_length=2)),
                ('certificate_file', models.FileField(null=True, upload_to='files/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
