# Generated by Django 4.1.2 on 2022-11-26 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_student_semester'),
        ('certificates', '0002_alter_certificate_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.student'),
        ),
    ]
