# Generated by Django 4.1.2 on 2022-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.CharField(choices=[('NA', 'NATIONAL'), ('SE', 'STATE'), ('CO', 'COLLEGE'), ('MC', 'MOOC_COURSE')], default=0, max_length=2),
        ),
    ]
