# Generated by Django 4.1.2 on 2022-11-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.CharField(choices=[('NA', 'NATIONAL EVENT E'), ('SE', 'STATE EVENT'), ('CO', 'COLLEGE EVENT'), ('MC', 'MOOC COURSE')], default=0, max_length=2),
        ),
    ]
