# Generated by Django 4.1.2 on 2022-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_alter_certificate_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.CharField(choices=[('NA', 'NATIONAL EVENT E'), ('SE', 'STATE EVENT'), ('CO', 'COLLEGE EVENT'), ('MC', 'MOOC COURSE')], default=None, max_length=2),
        ),
    ]
