# Generated by Django 4.1.2 on 2022-11-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
