# Generated by Django 4.1.2 on 2022-11-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_editsubject_class_belongs'),
        ('attendence', '0002_attendence_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class'),
        ),
    ]
