# Generated by Django 4.1.2 on 2022-11-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_editsubject_semester'),
        ('attendence', '0005_attendence_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='class_belongs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class'),
        ),
    ]
