# Generated by Django 4.1.2 on 2022-12-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_attendence_class_belongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='hour',
            field=models.CharField(blank=True, choices=[('H1', 'FIrst hour'), ('H2', 'Second hour'), ('H3', 'Third hour'), ('H4', 'Fourth hour'), ('H5', 'Fifth hour'), ('H6', 'Sixsth hour')], max_length=3),
        ),
    ]
