# Generated by Django 4.1.2 on 2022-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('send_to', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
