# Generated by Django 4.1.2 on 2022-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rank',
            field=models.CharField(choices=[('F', 'F'), ('S', 'Teacher')], default=0, max_length=2),
        ),
    ]
