# Generated by Django 4.1.2 on 2022-11-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_rename_rank_assignment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('F', 'F'), ('S', 'S')], default=0, max_length=2),
        ),
    ]
