# Generated by Django 4.1.2 on 2022-12-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_semester_order'),
        ('assignment', '0010_submittedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='class_belongs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class'),
        ),
        migrations.AddField(
            model_name='submittedassignment',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester'),
        ),
        migrations.AddField(
            model_name='submittedassignment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
        ),
    ]
