# Generated by Django 4.1.2 on 2022-12-01 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0020_semester_order'),
        ('assignment', '0012_submittedassignment_submitted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored', models.CharField(max_length=4)),
                ('ouof', models.CharField(max_length=4)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('class_belongs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
