# Generated by Django 4.1.2 on 2022-12-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_assignmentmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentmark',
            old_name='ouof',
            new_name='outof',
        ),
    ]
