# Generated by Django 4.1.2 on 2022-12-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0015_alter_assignmentmark_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmark',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment'),
        ),
    ]
